# Generated by Django 3.2.8 on 2021-10-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=150)),
                ('difficulty', models.IntegerField()),
                ('extra_data', models.CharField(max_length=100)),
                ('gas_limit', models.IntegerField()),
                ('gas_used', models.IntegerField()),
                ('logs_bloom', models.TextField()),
                ('miner', models.CharField(max_length=42)),
                ('nonce', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('parent_hash', models.CharField(max_length=150)),
                ('receipt_root', models.CharField(max_length=150)),
                ('sha3_uncles', models.CharField(max_length=150)),
                ('size', models.IntegerField()),
                ('state_root', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField()),
                ('total_difficulty', models.IntegerField()),
                ('transactions_root', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date added to off-chain database')),
            ],
        ),
    ]
