# Generated by Django 3.2.8 on 2021-10-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='difficulty',
            field=models.BigIntegerField(),
        ),
    ]
