# Generated by Django 3.2.8 on 2021-10-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0003_alter_block_total_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
