# Generated by Django 3.2.8 on 2021-10-19 22:26

from django.db import migrations
import indexer.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0004_alter_block_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='difficulty',
            field=indexer.custom_fields.BiggerIntegerField(),
        ),
        migrations.AlterField(
            model_name='block',
            name='total_difficulty',
            field=indexer.custom_fields.BiggerIntegerField(),
        ),
    ]
