# Generated by Django 3.2.8 on 2021-10-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0005_auto_20211019_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TokenContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=150)),
                ('block_hash', models.CharField(max_length=150)),
                ('block_number', models.BigIntegerField()),
                ('from_address', models.CharField(max_length=150)),
                ('gas', models.BigIntegerField()),
                ('gas_price', models.BigIntegerField()),
                ('input', models.CharField(max_length=150)),
                ('max_fee_per_gas', models.BigIntegerField()),
                ('max_priority_fee_per_gas', models.BigIntegerField()),
                ('nonce', models.IntegerField()),
                ('to_address', models.CharField(max_length=150)),
                ('transaction_index', models.IntegerField()),
                ('value', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='block',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
