# Generated by Django 3.2.8 on 2021-10-21 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0006_auto_20211021_0002'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TokenContract',
            new_name='Contract',
        ),
    ]
