# Generated by Django 3.2.8 on 2021-10-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0011_auto_20211021_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(help_text='account address', max_length=42),
        ),
    ]
