# Generated by Django 3.2.8 on 2021-12-08 23:19

from django.db import migrations
import indexer.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0014_auto_20211208_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=indexer.custom_fields.BiggerIntegerField(),
        ),
    ]
