# Generated by Django 3.2.8 on 2021-12-08 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0016_remove_block_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 8, 23, 58, 52, 741244)),
            preserve_default=False,
        ),
    ]
