# Generated by Django 3.2.8 on 2021-12-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0017_block_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='hash',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='block',
            name='nonce',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='block',
            name='receipt_root',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='block',
            name='sha3_uncles',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='block',
            name='state_root',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='block',
            name='transactions_root',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='hash',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='input',
            field=models.CharField(max_length=500),
        ),
    ]
