# Generated by Django 3.2.8 on 2021-12-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0018_auto_20211215_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='input',
            field=models.TextField(),
        ),
    ]
