# Generated by Django 3.2.8 on 2021-12-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0019_alter_transaction_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hash',
            field=models.CharField(help_text='account address', max_length=42, unique=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='hash',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='hash',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
